#string - plain text....
name = "Metric"
#numbers/ integer ...
age = 19
#floats / decimal no's ...
Temp = 26.7
#boolean (True/False) ...
ismale=true
istall= false 
#nil (has no value) ...
flaws = nil
